# -*- coding: utf-8 -*-
"""clase_8_8 SEPTIEMBRE 2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16jQwncHgICq0Dkn2vVTOZEeearavjgbG
"""



"""<center>

#**COLEGIO SIGLO XXI - EL SOCORRO**
#**PRESENTADO A: ING PAOLA ANDREA QUINTERO**
#**PRESENTADO POR: MARÍA JOSE DURAN GÓMEZ**
#**GRADO DÉCIMO**
#**8 SEPTIEMBRE 2022**

#**¿Qué es Python?**
# Es un lenguaje de programación de alto nivel que se utiliza para desarrollar aplicaciones de todo tipo. A diferencia de otros lenguajes como Java o .NET, se trata de un lenguaje interpretado, es decir, que no es necesario compilarlo para ejecutar las aplicaciones escritas en Python, sino que se ejecutan directamente por el ordenador utilizando un programa denominado interpretador, por lo que no es necesario “traducirlo” a lenguaje máquina. 
#Fecha de lanzamiento: Python remonta su origen a principios de los años 90.
#Creadores: Guido Van Rossum, un trabajador del Centrum Wiskunde & Informatica (CWI)

#Recuperado de: https://www.becas-santander.com/es/blog/python-que-es.html
"""

print("Esto es una suma")
numero_uno = 5
numero_dos = 22
resultado = numero_uno + numero_dos
print(resultado)

print("Esto es una resta")
numero_uno = 35
numero_dos = 56
resultado = numero_uno - numero_dos
print(resultado)

print("Esto es una multiplicacion")
numero_uno = 5
numero_dos = 7
resultado = numero_uno * numero_dos
print(resultado)

print("Esto es una division")
numero_uno = 2
numero_dos = 56
resultado = numero_uno / numero_dos
print(resultado)

"""#Ejercicios de Tipos de Datos Simples

## Ejercicio 1
Escribir un programa que pregunte el nombre de el usuario en la consola y un número entero e imprima por pantalla una líneas distintas el nombre de el usuario tantas veces como el número introducido.
"""

peso = input("¿Cuál es tu peso en kg?")
estatura = input("¿Cuál es tu estatura en metros?")
imc = round(float(peso)/float(estatura)**2,2)
print("Tu índice de masa corporal es " + str(imc))

nombre = input("¿Cómo te llamas? ")
n = input("Introduce tu número entero: ")
print((nombre + "\n") * int(n))

"""## Ejercicio 2
Escribir un programa que pida al usuario su peso (en kg) y estatura (en metros), calcule el índice de masa corporal y lo almacene en una variable e imprima por pantalla la frase 'Tu índice de masa corporal es' <imc> donde <imc> es el índice de masa corporal calculando redondeando con dos decimales
"""

peso = input("¿Cuál es tu peso en kg?")
estatura = input("¿Cuál es tu estatura en metros?")
imc = round(float(peso)/float(estatura)**2,2)
print("Tu índice de masa corporal es " + str(imc))

"""##**LIBRERÍAS EN PYTHON**

**¿Qué es?**
  
  .0
"""